/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.duke.ece568.proj;
import proto.A2U.*;
import proto.U2A.*;
import proto.WorldAmazon.*;
import proto.WorldUps.*;


public class App {
    public String getGreeting() {
        return "Server Starts...";
    }

    public static void main(String[] args) {
        try {
            System.out.println(new App().getGreeting());
            AmazonServer amazonServer = new AmazonServer();
            amazonServer.setUpServer();
            amazonServer.go();
        }catch (Exception generalE){
            generalE.printStackTrace();
        }
    }
}
