# Generated by Django 3.2 on 2021-04-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0010_auto_20210418_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='product_default.jpg', upload_to='product_pics'),
        ),
    ]
