# Generated by Django 3.2 on 2021-04-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0011_alter_product_img'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='media_test',
        ),
    ]
