# Generated by Django 3.2 on 2021-04-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0012_alter_product_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='product_default.jpg', null=True, upload_to='product_pics', verbose_name='picture'),
        ),
    ]
