# Generated by Django 3.2 on 2021-04-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0018_order_complete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orderedProduct',
            new_name='OrderItem',
        ),
    ]
