# Generated by Django 3.2 on 2021-04-19 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0022_auto_20210419_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='products',
        ),
        migrations.AddField(
            model_name='package',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.orderitem'),
        ),
    ]
