# Generated by Django 3.2 on 2021-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0024_remove_package_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='transaction_id',
            new_name='UPS_id',
        ),
        migrations.AddField(
            model_name='package',
            name='track_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
