# Generated by Django 3.2 on 2021-04-20 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0025_auto_20210420_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.package'),
        ),
    ]
