# Generated by Django 3.2 on 2021-04-23 22:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0030_rename_track_id_package_truck_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
